sudo: required
services:
  - docker

before_install:
  - docker build -t tkealamakia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tkealamakia/react-test npm test -- --coverage

after_success:
  - docker build -t tkealamakia/multi-client ./client
  - docker build -t tkealamakia/multi-nginx ./nginx
  - docker build -t tkealamakia/multi-server ./server
  - docker build -t tkealamakia/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tkealamakia/multi-client
  - docker push tkealamakia/multi-nginx
  - docker push tkealamakia/multi-server
  - docker push tkealamakia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-998085235794
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
